@c -*-texinfo-*-
@c This is part of the GNU MDK Reference Manual.
@c Copyright (C) 2000, 2001, 2003, 2004, 2006
@c   Free Software Foundation, Inc.
@c See the file mdk.texi for copying conditions.

@node Concept Index, Instructions and commands, Copying, Top
@unnumbered Concept Index

@cindex tail recursion
@printindex cp

