@node Copying, Concept Index, Problems, Top
@appendix Copying

@menu
* GNU General Public License::
* GNU Free Documentation License::
@end menu

GNU MDK is distributed under the GNU General Public License (GPL) and
this manual under the GNU Free Documentation License (GFDL).

@node GNU General Public License, GNU Free Documentation License, Copying, Copying
@appendixsec GNU General Public License
@cindex GPL, GNU General Public License

@lowersections
@include gpl.texi
@raisesections



@node GNU Free Documentation License
@appendixsec GNU Free Documentation License

@cindex FDL, GNU Free Documentation License
@include fdl.texi

@c Local Variables:
@c ispell-local-pdict: "ispell-dict"
@c End:

